<?php
/**
 * Fired when the plugin is uninstalled.
 *
 * Cleans up options, transients, and metadata created by the plugin.
 *
 * @package GMB_Ranker_SEO_Automation
 * @since   2.1.0
 */

// If uninstall not called from WordPress, exit.
if (!defined('WP_UNINSTALL_PLUGIN')) {
    exit;
}

/**
 * Perform cleanup for a single site.
 */
function gmb_ranker_seo_uninstall_single_site() {
    global $wpdb;

    // 1. All plugin registered option names
    $options = array(
        'gmb_ranker_api_key',
        'gmb_ranker_auto_post_redirect',
        'gmb_ranker_redirects_rules',
        'gmb_ranker_404_logs',
        'gmb_ranker_indexed_urls',
        'gmb_ranker_google_indexing_json',
        'gmb_ranker_bing_api_key',
        'gmb_ranker_role_permissions',
        'gmb_ranker_local_locations',
        'gmb_ranker_wizard_completed',
        'gmb_strip_category_base',
        'gmb_seo_disable_xmlrpc',
        'gmb_seo_hide_wp_version',
        'gmb_seo_restrict_rest_api',
        'gmb_seo_enable_security_headers',
        'gmb_metadata_sep',
        'gmb_metadata_global_robots',
        'gmb_metadata_og_thumbnail',
        'gmb_metadata_twitter_card_type',
        'gmb_homepage_title_template',
        'gmb_homepage_desc_template',
        'gmb_homepage_robots_meta_enable',
        'gmb_homepage_robots_meta',
        'gmb_homepage_advanced_max_snippet',
        'gmb_homepage_advanced_max_video',
        'gmb_homepage_advanced_max_image',
        'gmb_homepage_facebook_title',
        'gmb_homepage_facebook_desc',
        'gmb_homepage_facebook_image',
        'gmb_homepage_twitter_card_type',
        'gmb_author_archives_enable',
        'gmb_author_base',
        'gmb_author_title_template',
        'gmb_author_desc_template',
        'gmb_author_robots_meta_enable',
        'gmb_author_robots_meta',
        'gmb_author_advanced_max_snippet',
        'gmb_author_advanced_max_video',
        'gmb_author_advanced_max_image',
        'gmb_author_slack_sharing',
        'gmb_author_seo_controls',
        'gmb_author_custom_fields',
        'gmb_author_thumbnail_watermark',
        'gmb_misc_date_archives_enable',
        'gmb_misc_disable_date_archives',
        'gmb_misc_date_archive_title',
        'gmb_misc_date_archive_desc',
        'gmb_misc_date_robots_meta_enable',
        'gmb_misc_date_robots_meta',
        'gmb_misc_date_advanced_max_snippet',
        'gmb_misc_date_advanced_max_video',
        'gmb_misc_date_advanced_max_image',
        'gmb_misc_search_archive_title',
        'gmb_misc_404_page_title',
        'gmb_misc_noindex_search_results',
        'gmb_misc_noindex_subpages',
        'gmb_misc_noindex_paginated_single',
        'gmb_misc_noindex_password_protected',
        'gmb_posts_title_template',
        'gmb_posts_desc_template',
        'gmb_posts_schema_type',
        'gmb_posts_schema_headline',
        'gmb_posts_schema_desc',
        'gmb_posts_schema_article_type',
        'gmb_posts_robots_meta_enable',
        'gmb_posts_robots_meta',
        'gmb_posts_advanced_max_snippet',
        'gmb_posts_advanced_max_video',
        'gmb_posts_advanced_max_image',
        'gmb_posts_twitter_card_type',
        'gmb_posts_link_suggestions',
        'gmb_posts_link_suggestion_titles',
        'gmb_posts_slack_sharing',
        'gmb_posts_seo_controls',
        'gmb_posts_bulk_editing',
        'gmb_posts_custom_fields',
        'gmb_posts_thumbnail_watermark',
        'gmb_pages_title_template',
        'gmb_pages_desc_template',
        'gmb_pages_schema_type',
        'gmb_pages_schema_headline',
        'gmb_pages_schema_desc',
        'gmb_pages_schema_article_type',
        'gmb_pages_robots_meta_enable',
        'gmb_pages_robots_meta',
        'gmb_pages_advanced_max_snippet',
        'gmb_pages_advanced_max_video',
        'gmb_pages_advanced_max_image',
        'gmb_pages_twitter_card_type',
        'gmb_pages_link_suggestions',
        'gmb_pages_link_suggestion_titles',
        'gmb_pages_slack_sharing',
        'gmb_pages_seo_controls',
        'gmb_pages_bulk_editing',
        'gmb_pages_custom_fields',
        'gmb_pages_thumbnail_watermark',
        'gmb_attachment_redirect_to_parent',
        'gmb_attachment_title_template',
        'gmb_attachment_desc_template',
        'gmb_attachment_robots_meta_enable',
        'gmb_attachment_robots_meta',
        'gmb_attachment_advanced_max_snippet',
        'gmb_attachment_advanced_max_video',
        'gmb_attachment_advanced_max_image',
        'gmb_attachment_twitter_card_type',
        'gmb_attachment_link_suggestions',
        'gmb_attachment_link_suggestion_titles',
        'gmb_attachment_slack_sharing',
        'gmb_attachment_seo_controls',
        'gmb_attachment_bulk_editing',
        'gmb_attachment_custom_fields',
        'gmb_attachment_thumbnail_watermark',
        'gmb_services_title_template',
        'gmb_services_desc_template',
        'gmb_services_schema_type',
        'gmb_services_schema_headline',
        'gmb_services_schema_desc',
        'gmb_services_schema_service_type',
        'gmb_services_robots_meta_enable',
        'gmb_services_robots_meta',
        'gmb_services_advanced_max_snippet',
        'gmb_services_advanced_max_video',
        'gmb_services_advanced_max_image',
        'gmb_services_twitter_card_type',
        'gmb_services_link_suggestions',
        'gmb_services_link_suggestion_titles',
        'gmb_services_slack_sharing',
        'gmb_services_seo_controls',
        'gmb_services_bulk_editing',
        'gmb_services_custom_fields',
        'gmb_services_thumbnail_watermark',
        'gmb_service_locations_title_template',
        'gmb_service_locations_desc_template',
        'gmb_service_locations_schema_type',
        'gmb_service_locations_schema_headline',
        'gmb_service_locations_schema_desc',
        'gmb_service_locations_schema_business_type',
        'gmb_service_locations_robots_meta_enable',
        'gmb_service_locations_robots_meta',
        'gmb_service_locations_advanced_max_snippet',
        'gmb_service_locations_advanced_max_video',
        'gmb_service_locations_advanced_max_image',
        'gmb_service_locations_twitter_card_type',
        'gmb_service_locations_link_suggestions',
        'gmb_service_locations_link_suggestion_titles',
        'gmb_service_locations_slack_sharing',
        'gmb_service_locations_seo_controls',
        'gmb_service_locations_bulk_editing',
        'gmb_service_locations_custom_fields',
        'gmb_service_locations_thumbnail_watermark',
        'gmb_team_members_title_template',
        'gmb_team_members_desc_template',
        'gmb_team_members_schema_type',
        'gmb_team_members_schema_headline',
        'gmb_team_members_schema_desc',
        'gmb_team_members_schema_job_title',
        'gmb_team_members_robots_meta_enable',
        'gmb_team_members_robots_meta',
        'gmb_team_members_advanced_max_snippet',
        'gmb_team_members_advanced_max_video',
        'gmb_team_members_advanced_max_image',
        'gmb_team_members_twitter_card_type',
        'gmb_team_members_link_suggestions',
        'gmb_team_members_link_suggestion_titles',
        'gmb_team_members_slack_sharing',
        'gmb_team_members_seo_controls',
        'gmb_team_members_bulk_editing',
        'gmb_team_members_custom_fields',
        'gmb_team_members_thumbnail_watermark',
        'gmb_categories_archive_title',
        'gmb_categories_archive_desc',
        'gmb_categories_robots_meta_enable',
        'gmb_categories_robots_meta',
        'gmb_categories_advanced_max_snippet',
        'gmb_categories_advanced_max_video',
        'gmb_categories_advanced_max_image',
        'gmb_categories_twitter_card_type',
        'gmb_categories_slack_sharing',
        'gmb_categories_seo_controls',
        'gmb_categories_bulk_editing',
        'gmb_categories_remove_snippet',
        'gmb_categories_custom_fields',
        'gmb_categories_thumbnail_watermark',
        'gmb_tags_archive_title',
        'gmb_tags_archive_desc',
        'gmb_tags_robots_meta_enable',
        'gmb_tags_robots_meta',
        'gmb_tags_slack_sharing',
        'gmb_tags_seo_controls',
        'gmb_tags_bulk_editing',
        'gmb_tags_remove_snippet',
        'gmb_tags_thumbnail_watermark',
        'gmb_social_facebook_page_url',
        'gmb_social_facebook_authorship',
        'gmb_social_facebook_admin',
        'gmb_social_facebook_app_id',
        'gmb_social_twitter_username',
        'gmb_social_additional_profiles',
        'gmb_local_seo_type',
        'gmb_local_seo_name',
        'gmb_local_seo_logo',
        'gmb_local_seo_phone',
        'gmb_local_seo_email',
        'gmb_local_seo_address_street',
        'gmb_local_seo_address_locality',
        'gmb_local_seo_address_region',
        'gmb_local_seo_address_postal',
        'gmb_local_seo_address_country',
        'gmb_local_seo_geo_lat',
        'gmb_local_seo_geo_lng',
        'gmb_local_seo_opening_hours',
        'gmb_local_seo_price_range',
        'gmb_local_seo_about_page',
        'gmb_local_seo_contact_page',
        'gmb_local_seo_maps_api_key',
        'gmb_local_seo_multiple_locations',
        'gmb_sitemap_items_per_page',
        'gmb_sitemap_include_images',
        'gmb_sitemap_include_featured_images',
        'gmb_sitemap_ping_search_engines',
        'gmb_sitemap_post_types',
        'gmb_sitemap_taxonomies',
        'gmb_sitemap_excluded_posts',
        'gmb_sitemap_excluded_terms',
        'gmb_auto_alt_text',
        'gmb_auto_title_text',
        'gmb_auto_caption_text',
        'gmb_auto_description_text',
        'gmb_add_missing_image_dimensions',
        'gmb_llmstxt_enable',
        'gmb_llmstxt_title',
        'gmb_llmstxt_summary',
        'gmb_llmstxt_notes',
        'gmb_llmstxt_post_types',
        'gmb_llmstxt_custom_links',
        'gmb_toc_enable',
        'gmb_toc_headings',
        'gmb_toc_title',
        'gmb_toc_post_types',
        'gmb_toc_position',
        'gmb_ai_provider',
        'gmb_ai_openai_key',
        'gmb_ai_claude_key',
        'gmb_ai_gemini_key',
        'gmb_ai_default_model',
        'gmb_ai_temperature',
        'gmb_ai_max_tokens',
    );

    // Module flags
    $module_keys = array(
        'gmb_ranker_module_metadata',
        'gmb_ranker_module_sitemaps',
        'gmb_ranker_module_redirects',
        'gmb_ranker_module_schema',
        'gmb_ranker_module_preferred_source',
        'gmb_ranker_module_image_seo',
        'gmb_ranker_module_links',
        'gmb_ranker_module_db_tools',
        'gmb_ranker_module_role_manager',
        'gmb_ranker_module_instant_indexing',
        'gmb_ranker_module_local_seo',
        'gmb_ranker_module_seo_analysis',
        'gmb_ranker_module_security',
        'gmb_ranker_module_llmstxt',
        'gmb_ranker_module_ai_provider',
        'gmb_ranker_module_toc',
    );

    $all_options = array_merge($options, $module_keys);

    foreach ($all_options as $opt) {
        delete_option($opt);
    }

    // 2. Delete all post meta created by plugin
    $wpdb->query("DELETE FROM {$wpdb->postmeta} WHERE meta_key LIKE '_gmb_ranker_%'");

    // 3. Delete all user meta created by plugin
    $wpdb->query("DELETE FROM {$wpdb->usermeta} WHERE meta_key LIKE '_gmb_ranker_%'");

    // 4. Delete all term meta created by plugin
    $wpdb->query("DELETE FROM {$wpdb->termmeta} WHERE meta_key LIKE '_gmb_ranker_%'");

    // 5. Clear transients
    $wpdb->query("DELETE FROM {$wpdb->options} WHERE option_name LIKE '_transient_gmb_%' OR option_name LIKE '_transient_timeout_gmb_%'");
}

// Execute cleanup for single site or all sites in a multisite network
if (is_multisite()) {
    $sites = get_sites(array('fields' => 'ids'));
    foreach ($sites as $site_id) {
        switch_to_blog($site_id);
        gmb_ranker_seo_uninstall_single_site();
        restore_current_blog();
    }
} else {
    gmb_ranker_seo_uninstall_single_site();
}
